---
title: "Predicting football matches"
output: html_document
---
TODO: add in team attributes to model data


```{r setup}
library(plyr)
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(foreach)
library(doParallel)
library(randomForest)
library(data.table)
library(tictoc)
```

##Initial look at data

```{r data}
dat<-src_sqlite("D:\\Downloads\\soccer\\database.sqlite",create = F)
src_tbls(dat)
```

```{r data_1}
matches<-tbl(dat,"Match") %>%  data.frame()
matches1<-filter(matches,is.na(home_player_X1)==F)
matches1$date<-ymd(as.POSIXct(matches1$date))
matches1$result<-ifelse(matches1$home_team_goal>matches1$away_team_goal,"Home",
                       ifelse(matches1$home_team_goal<matches1$away_team_goal,"Away","Draw"))
matches_player<-matches1 %>% 
  gather(key="Column",value="Value",-id) %>% 
  filter(grepl("player",Column)==T) %>% 
  filter(grepl("X|Y",Column)==F)
colnames(matches_player)[3]<-"player_api_id"

players_in_matches<-filter(tbl(dat,"Player"),player_api_id%in%matches_player$player_api_id) %>%data.frame () %>% select(-id)

players_in_matches$player_api_id<-as.character(players_in_matches$player_api_id)
players_1<-left_join(matches_player,players_in_matches) %>% filter(is.na(player_api_id)==F)

players_1$match_date<-matches1[match(players_1$id,matches1$id),6]


player_attributes<-filter(tbl(dat,"Player_Attributes"),player_api_id%in%players_1$player_api_id) %>% data.frame()
player_attributes$date<-ymd(as.POSIXct(player_attributes$date))
player_attributes$player_api_id<-as.character(player_attributes$player_api_id)
player_attributes<-data.table(player_attributes)
setkey(x = player_attributes,player_api_id)
players_1<-data.table(players_1)
setkey(players_1,player_api_id)

match_player_and_attributes<-function(player,players = players_1,attributes = player_attributes){
  dat1<-players[which(players$player_api_id==player),]
  att_1<-attributes[which(attributes$player_api_id==player),] %>% 
    select(-id)
  dat2<-left_join(dat1,att_1)
  dat2$diff<-abs(dat2$match_date-dat2$date)
  dat2$paste<-paste(dat2$id,dat2$diff,sep="_")
  dat3<-dat2 %>% group_by(id) %>% 
    dplyr::summarise(diff=min(diff)) %>% 
    mutate("paste"=paste(id,diff,sep="_"))
  dat4<-filter(dat2,paste%in%dat3$paste) %>% select(-diff,-paste)
  return(dat4)
}

#eg1<-match_player_and_attributes(playersList[100,1])
playersList<-unique(players_1$player_api_id)

#creating parallel backend
registerDoParallel(makeCluster(2))
players_2<-foreach(a = 1:length(playersList),.combine = "rbind",.packages = c("data.table","dplyr"),.export = c("players_1","player_attributes"))%dopar%{
  match_player_and_attributes(playersList[a])
}
```

We can then calculate the average stats for each team

```{r av per team}
homeOrAway<-data.frame(str_split_fixed(string = players_2$Column,pattern = "_",2),stringsAsFactors = F)

players_2$homeOrAway<-homeOrAway$X1

#will need to treat goalkeepers diferently
players_grouped<-players_2 %>% 
  select(-player_api_id,-player_name,-player_fifa_api_id,-birthday,-Column,-match_date,-defensive_work_rate,-attacking_work_rate,-date,-preferred_foot) %>% 
  gather(key="Metric",value="Value",-id,-homeOrAway) %>% 
  mutate("Value"=as.numeric(Value)) %>% 
  group_by(id,homeOrAway,Metric) %>% 
  summarise("Mean"=mean(Value,na.rm = T),"Median"=median(Value,na.rm = T),"Max"=max(Value,na.rm = T))

players_grouped_2<-players_grouped %>% 
  ungroup() %>% 
  gather(key="Column",value="Value",-id,-homeOrAway,-Metric) %>% 
  mutate("Col"=paste(Metric,Column,homeOrAway,sep="_")) %>% 
  select(-Column,-Metric,-homeOrAway) %>% 
  filter(is.na(Value)==F) %>% 
  filter(is.infinite(Value)==F) %>% 
  spread(key="Col",value="Value",fill=0)
```

We can then join this up with the match data

```{r join}
matches2<-select(matches1,id,home_team_api_id,away_team_api_id,result)
joinedData<-left_join(matches2,players_grouped_2)

```

```{r ramndomForest}
#getting two thirds of the data
rows<-sample(nrow(joinedData),nrow(joinedData)*2/3)
trainData<-joinedData[rows,]
testData<-joinedData[-rows,]

trainDataMinus<-select(trainData,-result,-id)
resultsTrain<-select(trainData,result) %>% 
  mutate("result"=as.factor(result))
testDataMins<-select(testData,-result,-id)
testResult<-select(testData,result) %>% 
  mutate("result"=as.factor(result))
set.seed(100)
model<-randomForest(x = trainDataMinus,xtest =testDataMins ,ytest = testResult$result,y = resultsTrain$result)

testResult$Predicted<-model$test$predicted

testResult$Correct<-ifelse(testResult$result==testResult$Predicted,1,0)

sum(testResult$Correct)

sum(testResult$Correct)/nrow(testResult)
```

```{r team attributes}
team_att<-tbl(dat,"Team_Attributes") %>%
  data.frame() %>% 
  gather(key="Column",value="Value",-id,-team_fifa_api_id,-team_api_id,-date) %>% 
  select(-id,-team_fifa_api_id) 
team_att$date<-ymd(as.POSIXct(team_att$date))

matches3<-select(matches1,id,date,home_team_api_id,away_team_api_id,result)

matchTeamAttr<-function(matchID,matchData,team_att=team_att){
  dat1<-filter(matchData,id==matchID)
  homeID<-dat1[1,3]
  awayID<-dat1[1,4]
  homeStat<-filter(team_att,team_api_id==homeID) %>% 
    filter(date<dat1$date)%>% 
      mutate("id"=matchID)
    
  if(nrow(homeStat)>0){
    homeStat<-filter(homeStat,date==max(homeStat$date)) 
  }
    awayStat<-filter(team_att,team_api_id==awayID) %>% 
    filter(date<dat1$date)%>% 
      mutate("id"=matchID)
  if(nrow(awayStat)>0){
    awayStat<-filter(awayStat,date==max(awayStat$date)) 
  }
    dat2<-full_join(homeStat,awayStat,by=names(homeStat))
    return(dat2)
}
aa<-matchTeamAttr(15014,matches3,team_att)

team_stats<-foreach(a = 1:nrow(matches3),.combine = "rbind",.errorhandling = "remove")%do%{
  matchTeamAttr(matches3[a,1],matches3,team_att)
}
```
